@host = http://localhost:3000/api/users

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcwMTA4OTgzNSwiZXhwIjoxNzAxMTMzMDM1fQ.TRANiXjljGkWrTfxHcBgY4PHlS53EQNJXH7snAd5aqA
### 내 정보 조회
GET {{host}}/me
Authorization: Bearer {{accessToken}}